// https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/android-grpc/services/emulator-controller/proto/emulator_controller.proto

// Copyright (C) 2018 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Note that if you add/remove methods in this file you must update
// the metrics sql as well ./android/scripts/gen-grpc-sql.py
//
// Please group deleted methods in a block including the date (MM/DD/YY)
// it was removed. This enables us to easily keep metrics around after removal
//
// List of deleted methods
// rpc iWasDeleted (03/12/12)
// ...

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file emulator_controller.proto (package android.emulation.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AudioFormat, AudioPacket, BatteryState, BrightnessValue, ClipData, DisplayConfigurations, DisplayMode, EmulatorStatus, Fingerprint, GpsState, Image, ImageFormat, InputEvent, KeyboardEvent, LogMessage, MouseEvent, Notification, PhoneCall, PhoneNumber, PhoneResponse, PhysicalModelValue, Posture, RotationRadian, SensorValue, SmsMessage, TouchEvent, Velocity, VmRunState, WheelEvent } from "./emulator_controller_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * An EmulatorController service lets you control the emulator.
 * Note that this is currently an experimental feature, and that the
 * service definition might change without notice. Use at your own risk!
 *
 * We use the following rough conventions:
 *
 * streamXXX --> streams values XXX (usually for emulator lifetime). Values
 *               are updated as soon as they become available.
 * getXXX    --> gets a single value XXX
 * setXXX    --> sets a single value XXX, does not returning state, these
 *               usually have an observable lasting side effect.
 * sendXXX   --> send a single event XXX, possibly returning state information.
 *               android usually responds to these events.
 *
 * @generated from service android.emulation.control.EmulatorController
 */
export const EmulatorController = {
  typeName: "android.emulation.control.EmulatorController",
  methods: {
    /**
     * set/get/stream the sensor data
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamSensor
     */
    streamSensor: {
      name: "streamSensor",
      I: SensorValue,
      O: SensorValue,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.getSensor
     */
    getSensor: {
      name: "getSensor",
      I: SensorValue,
      O: SensorValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.setSensor
     */
    setSensor: {
      name: "setSensor",
      I: SensorValue,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * set/get/stream the physical model, this is likely the one you are
     * looking for when you wish to modify the device state.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setPhysicalModel
     */
    setPhysicalModel: {
      name: "setPhysicalModel",
      I: PhysicalModelValue,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.getPhysicalModel
     */
    getPhysicalModel: {
      name: "getPhysicalModel",
      I: PhysicalModelValue,
      O: PhysicalModelValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.streamPhysicalModel
     */
    streamPhysicalModel: {
      name: "streamPhysicalModel",
      I: PhysicalModelValue,
      O: PhysicalModelValue,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Atomically set/get the current primary clipboard data.
     * Note that a call to setClipboard will result in an immediate
     * event for those who made a call to streamClipboard and are
     * on a different channel than the one used to set the clipboard.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setClipboard
     */
    setClipboard: {
      name: "setClipboard",
      I: ClipData,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.getClipboard
     */
    getClipboard: {
      name: "getClipboard",
      I: Empty,
      O: ClipData,
      kind: MethodKind.Unary,
    },
    /**
     * Streams the current data on the clipboard. This will immediately produce
     * a result with the current state of the clipboard after which the stream
     * will block and wait until a new clip event is available from the guest.
     * Calling the setClipboard method above will not result in generating a
     * clip event. It is possible to lose clipboard events if the clipboard
     * updates very rapidly.
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamClipboard
     */
    streamClipboard: {
      name: "streamClipboard",
      I: Empty,
      O: ClipData,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Set/get the battery to the given state.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setBattery
     */
    setBattery: {
      name: "setBattery",
      I: BatteryState,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.getBattery
     */
    getBattery: {
      name: "getBattery",
      I: Empty,
      O: BatteryState,
      kind: MethodKind.Unary,
    },
    /**
     * Set the state of the gps.
     * Note: Setting the gps position will not be reflected in the user
     * interface. Keep in mind that android usually only samples the gps at 1
     * hz.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setGps
     */
    setGps: {
      name: "setGps",
      I: GpsState,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Gets the latest gps state as delivered by the setGps call, or location ui
     * if active.
     *
     * Note: this is not necessarily the actual gps coordinate visible at the
     * time, due to gps sample frequency (usually 1hz).
     *
     * @generated from rpc android.emulation.control.EmulatorController.getGps
     */
    getGps: {
      name: "getGps",
      I: Empty,
      O: GpsState,
      kind: MethodKind.Unary,
    },
    /**
     * Simulate a touch event on the finger print sensor.
     *
     * @generated from rpc android.emulation.control.EmulatorController.sendFingerprint
     */
    sendFingerprint: {
      name: "sendFingerprint",
      I: Fingerprint,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Send a keyboard event. Translating the event.
     *
     * @generated from rpc android.emulation.control.EmulatorController.sendKey
     */
    sendKey: {
      name: "sendKey",
      I: KeyboardEvent,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Send touch/mouse events. Note that mouse events can be simulated
     * by touch events.
     *
     * @generated from rpc android.emulation.control.EmulatorController.sendTouch
     */
    sendTouch: {
      name: "sendTouch",
      I: TouchEvent,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.sendMouse
     */
    sendMouse: {
      name: "sendMouse",
      I: MouseEvent,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc android.emulation.control.EmulatorController.injectWheel
     */
    injectWheel: {
      name: "injectWheel",
      I: WheelEvent,
      O: Empty,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * Stream a series of input events to the emulator, the events will
     * arrive in order.
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamInputEvent
     */
    streamInputEvent: {
      name: "streamInputEvent",
      I: InputEvent,
      O: Empty,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * Make a phone call.
     *
     * @generated from rpc android.emulation.control.EmulatorController.sendPhone
     */
    sendPhone: {
      name: "sendPhone",
      I: PhoneCall,
      O: PhoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends an sms message to the emulator.
     *
     * @generated from rpc android.emulation.control.EmulatorController.sendSms
     */
    sendSms: {
      name: "sendSms",
      I: SmsMessage,
      O: PhoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends an sms message to the emulator.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setPhoneNumber
     */
    setPhoneNumber: {
      name: "setPhoneNumber",
      I: PhoneNumber,
      O: PhoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieve the status of the emulator. This will contain general
     * hardware information, and whether the device has booted or not.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getStatus
     */
    getStatus: {
      name: "getStatus",
      I: Empty,
      O: EmulatorStatus,
      kind: MethodKind.Unary,
    },
    /**
     * Gets an individual screenshot in the desired format.
     *
     * The image will be scaled to the desired ImageFormat, while maintaining
     * the aspect ratio. The returned image will never exceed resolution of the
     * device display. Not setting the width or height (i.e. they are 0) will
     * result in using the display width and height.
     *
     * The resulting image will be properly oriented and can be displayed
     * directly without post processing. For example, if the device has a
     * 1080x1920 screen and is in landscape mode and called with no width or
     * height parameter, it will return a 1920x1080 image.
     *
     * The dimensions of the returned image will never exceed the corresponding
     * display dimensions. For example, this method will return a 1920x1080
     * screenshot, if the display resolution is 1080x1920 and a screenshot of
     * 2048x2048 is requested when the device is in landscape mode.
     *
     * This method will return an empty image if the display is not visible.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getScreenshot
     */
    getScreenshot: {
      name: "getScreenshot",
      I: ImageFormat,
      O: Image,
      kind: MethodKind.Unary,
    },
    /**
     * Streams a series of screenshots in the desired format.
     *
     * A new frame will be delivered whenever the device produces a new frame.
     * Beware that this can produce a significant amount of data and that
     * certain translations can be very costly. For example, streaming a series
     * of png images is very cpu intensive.
     *
     * Images are produced according to the getScreenshot API described above.
     *
     * If the display is inactive, or becomes inactive, an empty image will be
     * delivered. Images will be delived again if the display becomes active and
     * new frames are produced.
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamScreenshot
     */
    streamScreenshot: {
      name: "streamScreenshot",
      I: ImageFormat,
      O: Image,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Streams a series of audio packets in the desired format.
     * A new frame will be delivered whenever the emulated device
     * produces a new audio frame. You can expect packets to be
     * delivered in intervals of 20-30ms.
     *
     * Be aware that this can block when the emulator does not
     * produce any audio whatsoever!
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamAudio
     */
    streamAudio: {
      name: "streamAudio",
      I: AudioFormat,
      O: AudioPacket,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Injects a series of audio packets to the android microphone.
     * A new frame will be delivered whenever the emulated device
     * requests a new audio frame. Audio is usually delivered at a rate
     * that the emulator is requesting frames. Audio will be stored in a
     * temporary buffer that can hold 300ms of audio.
     *
     * Notes:
     *  - Only the first audio format packet that is delivered will be
     * honored. There is no need to send the audio format multiple times.
     *  - Real time audio currently immediately overrides the buffer. This
     * means you must provide a constant rate of audio packets. The real
     * time mode is experimental. Timestamps of audio packets might be
     * used in the future to improve synchronization.
     *
     * -  INVALID_ARGUMENT (code 3) The sampling rate was too high/low
     * -  INVALID_ARGUMENT (code 3) The audio packet was too large to handle.
     * -  FAILED_PRECONDITION (code 9) If there was a microphone registered
     * already.
     *
     * @generated from rpc android.emulation.control.EmulatorController.injectAudio
     */
    injectAudio: {
      name: "injectAudio",
      I: AudioPacket,
      O: Empty,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * Deprecated, please use the streamLogcat method instead.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getLogcat
     * @deprecated
     */
    getLogcat: {
      name: "getLogcat",
      I: LogMessage,
      O: LogMessage,
      kind: MethodKind.Unary,
    },
    /**
     * Streams the logcat output from the emulator.
     * Note that parsed logcat messages are only available after L (Api >23)
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamLogcat
     */
    streamLogcat: {
      name: "streamLogcat",
      I: LogMessage,
      O: LogMessage,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Transition the virtual machine to the desired state. Note that
     * some states are only observable. For example you cannot transition
     * to the error state.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setVmState
     */
    setVmState: {
      name: "setVmState",
      I: VmRunState,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Gets the state of the virtual machine.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getVmState
     */
    getVmState: {
      name: "getVmState",
      I: Empty,
      O: VmRunState,
      kind: MethodKind.Unary,
    },
    /**
     * Atomically changes the current multi-display configuration.
     * After this call the given display configurations will be activated. You
     * can only update secondary displays. Displays with id 0 will be ignored.
     *
     * This call can result in the removal or addition of secondary displays,
     * the final display state can be observed by the returned configuration.
     *
     * The following gRPC error codes can be returned:
     * -  FAILED_PRECONDITION (code 9) if the AVD does not support a
     * configurable
     *    secondary display.
     * -  INVALID_ARGUMENT (code 3) if:
     *     - The same display id is defined multiple times.
     *     - The display configurations are outside valid ranges.
     *       See DisplayConfiguration for details on valid ranges.
     * -  INTERNAL (code 13) if there was an internal emulator failure.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setDisplayConfigurations
     */
    setDisplayConfigurations: {
      name: "setDisplayConfigurations",
      I: DisplayConfigurations,
      O: DisplayConfigurations,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all currently valid logical displays.
     *
     * The gRPC error code FAILED_PRECONDITION (code 9) is returned if the AVD
     * does not support a configurable secondary display.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getDisplayConfigurations
     */
    getDisplayConfigurations: {
      name: "getDisplayConfigurations",
      I: Empty,
      O: DisplayConfigurations,
      kind: MethodKind.Unary,
    },
    /**
     * Notifies client of the following changes:
     *
     * - Virtual scene camera status change.
     * - Display configuration changes from extended ui. This will only be fired
     *   if the user makes modifications the extended displays through the
     *   extended control tab.
     *
     * Note that this method will send the initial virtual scene state
     * immediately.
     *
     * @generated from rpc android.emulation.control.EmulatorController.streamNotification
     */
    streamNotification: {
      name: "streamNotification",
      I: Empty,
      O: Notification,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Rotation angles are relative to the camera's current orientation.
     * The coordinate system is right-handed and is defined as follows:
     *   x axis is pointing right
     *   y axis is pointing up
     *   z axis is pointing towards the viewer
     * The z component of rotation is not used when calling this method.
     *
     * @generated from rpc android.emulation.control.EmulatorController.rotateVirtualSceneCamera
     */
    rotateVirtualSceneCamera: {
      name: "rotateVirtualSceneCamera",
      I: RotationRadian,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Velocity is absolute and is measured in meters per second.
     * The coordinate system is right-handed and is defined as follows:
     *   x axis is pointing right
     *   y axis is pointing up
     *   z axis is pointing towards the viewer
     *
     * @generated from rpc android.emulation.control.EmulatorController.setVirtualSceneCameraVelocity
     */
    setVirtualSceneCameraVelocity: {
      name: "setVirtualSceneCameraVelocity",
      I: Velocity,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Set foldable posture
     *
     * @generated from rpc android.emulation.control.EmulatorController.setPosture
     */
    setPosture: {
      name: "setPosture",
      I: Posture,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Get the backlight brightness.
     * The following gRPC error codes can be returned:
     * -  FAILED_PRECONDITION (code 9) if the AVD does not support hw-control.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getBrightness
     */
    getBrightness: {
      name: "getBrightness",
      I: BrightnessValue,
      O: BrightnessValue,
      kind: MethodKind.Unary,
    },
    /**
     * Set the backlight brightness.
     * The following gRPC error codes can be returned:
     * -  FAILED_PRECONDITION (code 9) if the AVD does not support hw-control.
     * -  INVALID_ARGUMENT (code 3) The brightness exceeds the valid range.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setBrightness
     */
    setBrightness: {
      name: "setBrightness",
      I: BrightnessValue,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the current mode of the primary display of a resizable AVD.
     * The following gRPC error codes can be returned:
     * -  FAILED_PRECONDITION (code 9) if the AVD is not resizable.
     *
     * @generated from rpc android.emulation.control.EmulatorController.getDisplayMode
     */
    getDisplayMode: {
      name: "getDisplayMode",
      I: Empty,
      O: DisplayMode,
      kind: MethodKind.Unary,
    },
    /**
     * Sets the size of the primary display of a resizable AVD. Fails if the AVD
     * is not resizable. The following gRPC error codes can be returned:
     * -  FAILED_PRECONDITION (code 9) if the AVD is not resizable.
     *
     * @generated from rpc android.emulation.control.EmulatorController.setDisplayMode
     */
    setDisplayMode: {
      name: "setDisplayMode",
      I: DisplayMode,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

