// https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/android-webrtc/android-webrtc/rtc_service.proto

// Copyright (C) 2018 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Note that if you add/remove methods in this file you must update
// the metrics sql as well by running ./android/scripts/gen-grpc-sql.py
//
// Please group deleted methods in a block including the date (MM/DD/YY)
// it was removed. This enables us to easily keep metrics around after removal
//
// List of deleted methods
// rpc iWasDeleted (03/12/12)
// ...

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file rtc_service.proto (package android.emulation.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { JsepMsg, RtcId } from "./rtc_service_pb.js";

/**
 * An RTC service lets you interact with the emulator through WebRTC
 * Note that this is currently an experimental feature, and that the
 * service definition might change without notice. Use at your own risk!
 *
 * The following endpoints are needed to establish the webrtc protocol
 * Due to limitiations in Javascript we cannot make use of bidirectional
 * endpoints See this [blog](https://grpc.io/blog/state-of-grpc-web) for
 * details.
 *
 * @generated from service android.emulation.control.Rtc
 */
export const Rtc = {
  typeName: "android.emulation.control.Rtc",
  methods: {
    /**
     * This function will generate a new identifier that the client
     * should use for further interaction. It will initiate the
     * JSEP protocol on the server side.
     *
     * @generated from rpc android.emulation.control.Rtc.requestRtcStream
     */
    requestRtcStream: {
      name: "requestRtcStream",
      I: Empty,
      O: RtcId,
      kind: MethodKind.Unary,
    },
    /**
     * Sends the given JsepMsg to the server. The RtcId in the
     * message should point to an active stream negotiation in
     * progress, otherwise the message will be ignored.
     *
     * @generated from rpc android.emulation.control.Rtc.sendJsepMessage
     */
    sendJsepMessage: {
      name: "sendJsepMessage",
      I: JsepMsg,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Reads an available jsep messages for the given client id,
     * blocking until one becomes available. Do not use the polling version
     * above if you opt for this one.
     *
     * The ice candidates for example will trickle in on this callback,
     * as will the SDP negotation.
     *
     * @generated from rpc android.emulation.control.Rtc.receiveJsepMessages
     */
    receiveJsepMessages: {
      name: "receiveJsepMessages",
      I: RtcId,
      O: JsepMsg,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * [DEPRECATED] This is only here as the go grpc webproxy used
     * by fuchsia does not support server side streaming. This method
     * will be removed in the future and should not be relied upon.
     *
     * Reads an available jsep messages for the given client id,
     * blocking until one becomes available. Do not use the polling version
     * above if you opt for this one.
     *
     * The ice candidates for example will trickle in on this callback,
     * as will the SDP negotation.
     *
     * @generated from rpc android.emulation.control.Rtc.receiveJsepMessage
     */
    receiveJsepMessage: {
      name: "receiveJsepMessage",
      I: RtcId,
      O: JsepMsg,
      kind: MethodKind.Unary,
    },
  }
} as const;

