// https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/android-webrtc/android-webrtc/rtc_service.proto

// Copyright (C) 2018 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Note that if you add/remove methods in this file you must update
// the metrics sql as well by running ./android/scripts/gen-grpc-sql.py
//
// Please group deleted methods in a block including the date (MM/DD/YY)
// it was removed. This enables us to easily keep metrics around after removal
//
// List of deleted methods
// rpc iWasDeleted (03/12/12)
// ...

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file rtc_service.proto (package android.emulation.control, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message android.emulation.control.RtcId
 */
export class RtcId extends Message<RtcId> {
  /**
   * The unique identifier of this connection. You will have to use the
   * same identifier when sending/receiving messages. The server will
   * generate a guid when receiving the start message.
   *
   * @generated from field: string guid = 1;
   */
  guid = "";

  constructor(data?: PartialMessage<RtcId>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "android.emulation.control.RtcId";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "guid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RtcId {
    return new RtcId().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RtcId {
    return new RtcId().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RtcId {
    return new RtcId().fromJsonString(jsonString, options);
  }

  static equals(a: RtcId | PlainMessage<RtcId> | undefined, b: RtcId | PlainMessage<RtcId> | undefined): boolean {
    return proto3.util.equals(RtcId, a, b);
  }
}

/**
 * @generated from message android.emulation.control.JsepMsg
 */
export class JsepMsg extends Message<JsepMsg> {
  /**
   * The unique identifier of this connection. You will have to use the
   * same identifier when sending/receiving messages. The server will
   * generate a guid when receiving the start message.
   *
   * @generated from field: android.emulation.control.RtcId id = 1;
   */
  id?: RtcId;

  /**
   * The JSON payload. This usually can be directly handled by the
   * Javascript library.
   *
   * The dictionary can contain the following properties
   *
   * - bye:
   *        You can hang up now. No new message expected for you.
   *        The server has stopped the RTC stream.
   *
   * - start:
   *        An RTCConfiguration dictionary providing options to
   *        configure the new connection. This can include the
   *        turn configuration the serve is using. This dictionary can be
   *        passed in directly to the
   *        [RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection)
   *        object.
   *
   * - candidate:
   *        The WebRTC API's RTCIceCandidateInit dictionary, which
   *        contains the information needed to fundamentally describe an
   *        RTCIceCandidate. See
   *        [RTCIceCandidate](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate)
   *        and [Session
   *        Lifetime](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Session_lifetime)
   *        for more details.
   *
   * - sdp:
   *        RTCSessionDescriptionInit dictionary containing the values
   *        to that can be assigned to a
   *        [RTCSessionDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription)
   *
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<JsepMsg>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "android.emulation.control.JsepMsg";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: RtcId },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JsepMsg {
    return new JsepMsg().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JsepMsg {
    return new JsepMsg().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JsepMsg {
    return new JsepMsg().fromJsonString(jsonString, options);
  }

  static equals(a: JsepMsg | PlainMessage<JsepMsg> | undefined, b: JsepMsg | PlainMessage<JsepMsg> | undefined): boolean {
    return proto3.util.equals(JsepMsg, a, b);
  }
}

